/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Logos' : null } |
  { 'Print' : null } |
  { 'Thumbnails' : null } |
  { 'Packaging' : null } |
  { 'SocialMedia' : null } |
  { 'Posters' : null };
export interface FeaturedItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'projectId' : bigint,
}
export interface Message {
  'messageId' : string,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'category' : Category,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : Category,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, string, Category, boolean],
    undefined
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getFeaturedSliderItems' : ActorMethod<[], Array<FeaturedItem>>,
  'getMessagesByCategory' : ActorMethod<[Category], Array<Message>>,
  'getProjectsByCategory' : ActorMethod<[Category], Array<Project>>,
  'getProjectsByCategoryName' : ActorMethod<[string], Array<Project>>,
  'getUnreadMessages' : ActorMethod<[], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, Category],
    boolean
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, Category, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];