/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'Logos' : IDL.Null,
  'Print' : IDL.Null,
  'Thumbnails' : IDL.Null,
  'Packaging' : IDL.Null,
  'SocialMedia' : IDL.Null,
  'Posters' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'messageId' : IDL.Text,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'category' : Category,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FeaturedItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'projectId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Bool],
      [],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getFeaturedSliderItems' : IDL.Func([], [IDL.Vec(FeaturedItem)], ['query']),
  'getMessagesByCategory' : IDL.Func([Category], [IDL.Vec(Message)], ['query']),
  'getProjectsByCategory' : IDL.Func([Category], [IDL.Vec(Project)], ['query']),
  'getProjectsByCategoryName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Category],
      [IDL.Bool],
      [],
    ),
  'updateProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Category, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Logos' : IDL.Null,
    'Print' : IDL.Null,
    'Thumbnails' : IDL.Null,
    'Packaging' : IDL.Null,
    'SocialMedia' : IDL.Null,
    'Posters' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'messageId' : IDL.Text,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'category' : Category,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FeaturedItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Bool],
        [],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getFeaturedSliderItems' : IDL.Func([], [IDL.Vec(FeaturedItem)], ['query']),
    'getMessagesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProjectsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getProjectsByCategoryName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Category],
        [IDL.Bool],
        [],
      ),
    'updateProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Category, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };